// lib/match-schedule.ts

import { initialGroups } from "@/lib/tournament";

export type ScheduleMatch = {
  id: string;
  matchNumber: number;
  date: string;
  time: string;
  homeTeam: string;
  awayTeam: string;
  stage: "group" | "knockout";
  groupLetter: string;
  groupName: string;
  tvChannel?: string;
  streamingChannel?: string;
};

const DEFAULT_TV_CHANNEL = "TV-kanal saknas";
const DEFAULT_STREAMING_CHANNEL = "";

const tvChannelByMatchNumber: Record<number, string> = {
  1: "TV4",
  2: "TV4",
  3: "SVT",
  4: "TV4",
  5: "SVT",
  6: "TV4",
  7: "TV4",
  8: "TV4",
  9: "TV4",
  10: "TV4",
  11: "TV4",
  12: "TV4",
  13: "TV4",
  14: "SVT",
  15: "TV4",
  16: "SVT",
  17: "SVT",
  18: "TV4",
  19: "TV4",
  20: "TV4",
  21: "TV4",
  22: "TV4",
  23: "TV4",
  24: "TV4",
  25: "TV4",
  26: "TV4",
  27: "TV4",
  28: "TV4",
  29: "TV4",
  30: "SVT",
  31: "TV4",
  32: "SVT",
  33: "TV4",
  34: "TV4",
  35: "TV4",
  36: "SVT",
  37: "TV4",
  38: "TV4",
  39: "TV4",
  40: "TV4",
  41: "SVT",
  42: "SVT",
  43: "SVT",
  44: "TV4",
  45: "SVT",
  46: "TV4",
  47: "SVT",
  48: "SVT",
  49: "TV4",
  50: "TV4",
  51: "TV4",
  52: "TV4",
  53: "SVT",
  54: "SVT",
  55: "SVT",
  56: "SVT",
  57: "SVT",
  58: "SVT",
  59: "TV4",
  60: "TV4",
  61: "TV4",
  62: "TV4",
  63: "TV4",
  64: "TV4",
  65: "TV4",
  66: "TV4",
  67: "SVT",
  68: "SVT",
  69: "TV4",
  70: "TV4",
  71: "TV4",
  72: "TV4",
};

const knockoutSchedule: ScheduleMatch[] = [
  {
    id: "knockout-73",
    matchNumber: 73,
    date: "28 juni 2026",
    time: "21:00",
    homeTeam: "2A",
    awayTeam: "2B",
    stage: "knockout",
    groupLetter: "",
    groupName: "16-delsfinal",
    tvChannel: "TV4",
    streamingChannel: "TV4 Play",
  },
  {
    id: "knockout-74",
    matchNumber: 74,
    date: "29 juni 2026",
    time: "19:00",
    homeTeam: "1E",
    awayTeam: "3A/B/C/D/F",
    stage: "knockout",
    groupLetter: "",
    groupName: "16-delsfinal",
    tvChannel: "SVT",
    streamingChannel: "SVT Play",
  },
  {
    id: "knockout-75",
    matchNumber: 75,
    date: "29 juni 2026",
    time: "22:30",
    homeTeam: "1F",
    awayTeam: "2C",
    stage: "knockout",
    groupLetter: "",
    groupName: "16-delsfinal",
    tvChannel: "TV4",
    streamingChannel: "TV4 Play",
  },
  {
    id: "knockout-76",
    matchNumber: 76,
    date: "30 juni 2026",
    time: "03:00",
    homeTeam: "1C",
    awayTeam: "2F",
    stage: "knockout",
    groupLetter: "",
    groupName: "16-delsfinal",
    tvChannel: "SVT",
    streamingChannel: "SVT Play",
  },
  {
    id: "knockout-77",
    matchNumber: 77,
    date: "30 juni 2026",
    time: "19:00",
    homeTeam: "1I",
    awayTeam: "3C/D/F/G/H",
    stage: "knockout",
    groupLetter: "",
    groupName: "16-delsfinal",
    tvChannel: "TV4",
    streamingChannel: "TV4 Play",
  },
  {
    id: "knockout-78",
    matchNumber: 78,
    date: "30 juni 2026",
    time: "23:00",
    homeTeam: "2E",
    awayTeam: "2I",
    stage: "knockout",
    groupLetter: "",
    groupName: "16-delsfinal",
    tvChannel: "TV4",
    streamingChannel: "TV4 Play",
  },
  {
    id: "knockout-79",
    matchNumber: 79,
    date: "1 juli 2026",
    time: "03:00",
    homeTeam: "1A",
    awayTeam: "3C/E/F/H/I",
    stage: "knockout",
    groupLetter: "",
    groupName: "16-delsfinal",
    tvChannel: "TV4",
    streamingChannel: "TV4 Play",
  },
  {
    id: "knockout-80",
    matchNumber: 80,
    date: "1 juli 2026",
    time: "18:00",
    homeTeam: "1L",
    awayTeam: "3E/H/I/J/K",
    stage: "knockout",
    groupLetter: "",
    groupName: "16-delsfinal",
    tvChannel: "SVT",
    streamingChannel: "SVT Play",
  },
  {
    id: "knockout-81",
    matchNumber: 81,
    date: "1 juli 2026",
    time: "22:00",
    homeTeam: "1D",
    awayTeam: "3B/E/F/I/J",
    stage: "knockout",
    groupLetter: "",
    groupName: "16-delsfinal",
    tvChannel: "TV4",
    streamingChannel: "TV4 Play",
  },
  {
    id: "knockout-82",
    matchNumber: 82,
    date: "2 juli 2026",
    time: "02:00",
    homeTeam: "1G",
    awayTeam: "3A/E/H/I/J",
    stage: "knockout",
    groupLetter: "",
    groupName: "16-delsfinal",
    tvChannel: "TV4",
    streamingChannel: "TV4 Play",
  },
  {
    id: "knockout-83",
    matchNumber: 83,
    date: "2 juli 2026",
    time: "21:00",
    homeTeam: "2K",
    awayTeam: "2L",
    stage: "knockout",
    groupLetter: "",
    groupName: "16-delsfinal",
    tvChannel: "SVT",
    streamingChannel: "SVT Play",
  },
  {
    id: "knockout-84",
    matchNumber: 84,
    date: "3 juli 2026",
    time: "01:00",
    homeTeam: "1H",
    awayTeam: "2J",
    stage: "knockout",
    groupLetter: "",
    groupName: "16-delsfinal",
    tvChannel: "TV4",
    streamingChannel: "TV4 Play",
  },
  {
    id: "knockout-85",
    matchNumber: 85,
    date: "3 juli 2026",
    time: "05:00",
    homeTeam: "1B",
    awayTeam: "3E/F/G/I/J",
    stage: "knockout",
    groupLetter: "",
    groupName: "16-delsfinal",
    tvChannel: "TV4",
    streamingChannel: "TV4 Play",
  },
  {
    id: "knockout-86",
    matchNumber: 86,
    date: "3 juli 2026",
    time: "20:00",
    homeTeam: "1J",
    awayTeam: "2H",
    stage: "knockout",
    groupLetter: "",
    groupName: "16-delsfinal",
    tvChannel: "TV4",
    streamingChannel: "TV4 Play",
  },
  {
    id: "knockout-87",
    matchNumber: 87,
    date: "4 juli 2026",
    time: "00:00",
    homeTeam: "1K",
    awayTeam: "3D/E/I/J/L",
    stage: "knockout",
    groupLetter: "",
    groupName: "16-delsfinal",
    tvChannel: "SVT",
    streamingChannel: "SVT Play",
  },
  {
    id: "knockout-88",
    matchNumber: 88,
    date: "4 juli 2026",
    time: "03:30",
    homeTeam: "2D",
    awayTeam: "2G",
    stage: "knockout",
    groupLetter: "",
    groupName: "16-delsfinal",
    tvChannel: "TV4",
    streamingChannel: "TV4 Play",
  },

  {
    id: "knockout-89",
    matchNumber: 89,
    date: "4 juli 2026",
    time: "19:00",
    homeTeam: "V74",
    awayTeam: "V77",
    stage: "knockout",
    groupLetter: "",
    groupName: "Åttondelsfinal",
    tvChannel: "TV4",
    streamingChannel: "TV4 Play",
  },
  {
    id: "knockout-90",
    matchNumber: 90,
    date: "4 juli 2026",
    time: "23:00",
    homeTeam: "V73",
    awayTeam: "V75",
    stage: "knockout",
    groupLetter: "",
    groupName: "Åttondelsfinal",
    tvChannel: "SVT",
    streamingChannel: "SVT Play",
  },

  {
    id: "knockout-91",
    matchNumber: 91,
    date: "5 juli 2026",
    time: "22:00",
    homeTeam: "V76",
    awayTeam: "V78",
    stage: "knockout",
    groupLetter: "",
    groupName: "Åttondelsfinal",
    tvChannel: "TV4",
    streamingChannel: "TV4 Play",
  },

  {
    id: "knockout-92",
    matchNumber: 92,
    date: "6 juli 2026",
    time: "02:00",
    homeTeam: "V79",
    awayTeam: "V80",
    stage: "knockout",
    groupLetter: "",
    groupName: "Åttondelsfinal",
    tvChannel: "SVT",
    streamingChannel: "SVT Play",
  },

  {
    id: "knockout-93",
    matchNumber: 93,
    date: "6 juli 2026",
    time: "21:00",
    homeTeam: "V83",
    awayTeam: "V84",
    stage: "knockout",
    groupLetter: "",
    groupName: "Åttondelsfinal",
    tvChannel: "TV4",
    streamingChannel: "TV4 Play",
  },

  {
    id: "knockout-94",
    matchNumber: 94,
    date: "7 juli 2026",
    time: "02:00",
    homeTeam: "V81",
    awayTeam: "V82",
    stage: "knockout",
    groupLetter: "",
    groupName: "Åttondelsfinal",
    tvChannel: "TV4",
    streamingChannel: "TV4 Play",
  },

  {
    id: "knockout-95",
    matchNumber: 95,
    date: "7 juli 2026",
    time: "18:00",
    homeTeam: "V86",
    awayTeam: "V88",
    stage: "knockout",
    groupLetter: "",
    groupName: "Åttondelsfinal",
    tvChannel: "TV4",
    streamingChannel: "TV4 Play",
  },

  {
    id: "knockout-96",
    matchNumber: 96,
    date: "7 juli 2026",
    time: "22:00",
    homeTeam: "V85",
    awayTeam: "V87",
    stage: "knockout",
    groupLetter: "",
    groupName: "Åttondelsfinal",
    tvChannel: "SVT",
    streamingChannel: "SVT Play",
  },

  {
    id: "knockout-97",
    matchNumber: 97,
    date: "9 juli 2026",
    time: "22:00",
    homeTeam: "V89",
    awayTeam: "V90",
    stage: "knockout",
    groupLetter: "",
    groupName: "Kvartsfinal",
    tvChannel: "TV4",
    streamingChannel: "TV4 Play",
  },

  {
    id: "knockout-98",
    matchNumber: 98,
    date: "10 juli 2026",
    time: "21:00",
    homeTeam: "V93",
    awayTeam: "V94",
    stage: "knockout",
    groupLetter: "",
    groupName: "Kvartsfinal",
    tvChannel: "SVT",
    streamingChannel: "SVT Play",
  },

  {
    id: "knockout-99",
    matchNumber: 99,
    date: "11 juli 2026",
    time: "23:00",
    homeTeam: "V91",
    awayTeam: "V92",
    stage: "knockout",
    groupLetter: "",
    groupName: "Kvartsfinal",
    tvChannel: "TV4",
    streamingChannel: "TV4 Play",
  },

  {
    id: "knockout-100",
    matchNumber: 100,
    date: "12 juli 2026",
    time: "03:00",
    homeTeam: "V95",
    awayTeam: "V96",
    stage: "knockout",
    groupLetter: "",
    groupName: "Kvartsfinal",
    tvChannel: "SVT",
    streamingChannel: "SVT Play",
  },

  {
    id: "knockout-101",
    matchNumber: 101,
    date: "14 juli 2026",
    time: "21:00",
    homeTeam: "V97",
    awayTeam: "V98",
    stage: "knockout",
    groupLetter: "",
    groupName: "Semifinal",
    tvChannel: "SVT",
    streamingChannel: "SVT Play",
  },

  {
    id: "knockout-102",
    matchNumber: 102,
    date: "15 juli 2026",
    time: "21:00",
    homeTeam: "V99",
    awayTeam: "V100",
    stage: "knockout",
    groupLetter: "",
    groupName: "Semifinal",
    tvChannel: "TV4",
    streamingChannel: "TV4 Play",
  },

  {
    id: "knockout-103",
    matchNumber: 103,
    date: "18 juli 2026",
    time: "23:00",
    homeTeam: "F101",
    awayTeam: "F102",
    stage: "knockout",
    groupLetter: "",
    groupName: "Bronsmatch",
    tvChannel: "SVT",
    streamingChannel: "SVT Play",
  },

  {
    id: "knockout-104",
    matchNumber: 104,
    date: "19 juli 2026",
    time: "21:00",
    homeTeam: "V101",
    awayTeam: "V102",
    stage: "knockout",
    groupLetter: "",
    groupName: "VM-final",
    tvChannel: "TV4",
    streamingChannel: "TV4 Play",
  },
];

const streamingChannelByMatchNumber: Record<number, string> =
  Object.fromEntries(
    Object.entries(tvChannelByMatchNumber).map(([key, channel]) => [
      Number(key),
      channel === "SVT" ? "SVT Play" : "TV4 Play",
    ])
  );

const timeOverrideByMatchNumber: Record<number, string> = {
  12: "04:00",
  20: "06:00",
  24: "04:00",
  43: "19:00",
  44: "05:00",
  48: "04:00",
  57: "01:00",
  58: "01:00",
  63: "05:00",
  64: "05:00",
  66: "02:00",
  69: "04:00",
  70: "04:00",
};

function getGroupLetter(groupName: string) {
  return groupName.replace("Grupp ", "").trim();
}

function getDateSortValue(date: string, time: string) {
  const [dayText, monthText] = date.split(" ");
  const day = Number(dayText);
  const monthMap: Record<string, number> = {
    juni: 5,
    juli: 6,
  };

  const month = monthMap[monthText] ?? 0;
  const [hour, minute] = time.split(":").map(Number);

  return new Date(2026, month, day, hour, minute).getTime();
}

export function getGroupStageSchedule(): ScheduleMatch[] {
  const groupSchedule = initialGroups.flatMap((group) =>
    group.matches.map((match) => ({
      id: `group-${match.matchNumber}`,
      matchNumber: match.matchNumber,
      date: match.date,
      time: timeOverrideByMatchNumber[match.matchNumber] ?? match.time,
      homeTeam: match.homeTeam,
      awayTeam: match.awayTeam,
      stage: "group" as const,
      groupLetter: getGroupLetter(group.name),
      groupName: group.name,
      tvChannel: tvChannelByMatchNumber[match.matchNumber] ?? DEFAULT_TV_CHANNEL,
      streamingChannel:
        streamingChannelByMatchNumber[match.matchNumber] ??
        DEFAULT_STREAMING_CHANNEL,
    }))
  );

  return [...groupSchedule, ...knockoutSchedule].sort(
    (a, b) =>
      getDateSortValue(a.date, a.time) - getDateSortValue(b.date, b.time)
  );
}

export function getScheduleMatchByNumber(matchNumber: number) {
  return getGroupStageSchedule().find(
    (match) => match.matchNumber === matchNumber
  );
}